name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  test_docker:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Chrome
      run: sudo apt-get install -y chromium-browser
      
    - name: Install Dependencies
      run: pip install webdriver-manager selenium packaging pandas dash sklearn statsmodels

    - name: Start Web Server
      run: python src/main.py &
           sleep 20
      
    - name: Run Selenium test script
      run: python test.py
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASSWORD }}'
        
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        tags: jared2812/csc302:latest
        
      
